### ISSUE TITLE
Supports NATed clients ?

### ISSUE THREAD

**Issue by joeblew99** [mdlayher/wgdynamic-go#2]
Is this designed to support clients that are NATed ?

I have a situation where all clients are NATed, and am looking for a way to use wireguard.

**Comment by mdlayher** [comment]
This package is a library that supports the wg-dynamic protocol in Go. There is nothing NAT related in this package.

Both wg-dynamic and my supporting Go projects (this and https://github.com/mdlayher/wgipam which will be a wg-dynamic server) are in their early days, but if you have a use case you'd like to explore, the best place to do so at the moment is to discuss it on the mailing list: https://lists.zx2c4.com/mailman/listinfo/wireguard.

For what it's worth, I run an IPv4 NAT'd WireGuard subnet and since my router also handles NAT, there's no reason it wouldn't work to dole out NAT'd IPv4 addresses.

Closing as this isn't related to this library itself.
